<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ErickMorales.EntityFrameworkCore.QueryBudget</RootNamespace>
    <AssemblyName>ErickMorales.EntityFrameworkCore.QueryBudget.Core</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
